SELECT TOP (1000) [Activity Period]
      ,[Activity Period Start Date]
      ,[Operating Airline]
      ,[Operating Airline IATA Code]
      ,[Published Airline]
      ,[Published Airline IATA Code]
      ,[GEO Summary]
      ,[GEO Region]
      ,[Landing Aircraft Type]
      ,[Aircraft Body Type]
      ,[Aircraft Manufacturer]
      ,[Aircraft Model]
      ,[Aircraft Version]
      ,[Landing Count]
      ,[Total Landed Weight]
      ,[data_as_of]
      ,[data_loaded_at]
  FROM [Chinook].[dbo].[stg_sfo_data]
