SELECT TOP (1000) [RecordID]
      ,[CASE ID]
      ,[SOURCE]
      ,[DEPARTMENT]
      ,[WORK GROUP]
      ,[TYPE]
      ,[DETAIL]
      ,[CREATION DATE]
      ,[CREATION TIME]
      ,[STATUS]
      ,[EXCEEDED EST TIMEFRAME]
      ,[CLOSED DATE]
      ,[DAYS TO CLOSE]
      ,[STREET ADDRESS]
      ,[ZIP CODE]
      ,[NEIGHBORHOOD]
      ,[COUNTY]
      ,[POLICE DISTRICT]
      ,[PARCEL ID NO]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[CATEGORY1]
      ,[CATEGORY2]
      ,[CATEGORY3]
      ,[CreationDate_Out]
      ,[CreationTime_Out]
      ,[ClosedDate_Out]
      ,[Created_Dt]
      ,[Created_By]
  FROM [Call_Center_Kansas].[dbo].[stg_call_center_kansas]
